O=.
S=.
Dest=$O/example_format.exe $O/example_iostreams.exe $O/example_lexical_cast.exe $O/example_tokenizer.exe
Objs=$O/example_format.obj $O/example_iostreams.obj $O/example_lexical_cast.obj $O/example_tokenizer.obj
CPPFLAGS = -nologo /EHsc

$(Dest):

$(Objs):

clean:
	@-rm *.obj *.exe >/dev/null
